name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: itsfernandesb
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          snake_color: "#C084FC"        # Lilás suave (combina com seus botões)
          background: "#0D1117"         # Fundo escuro igual ao tema do GitHub
          grid_color: "#30363D"         # Cinza escuro para os quadradinhos vazios
          apple_color: "#22D3EE"        # Azul turquesa para os commits

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
