name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: itsfernandesb
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
          snake_color: "#BA82E2"        # Roxo neon
          background: "#000000"         # Fundo preto
          grid_color: "#39FF14"         # Quadradinhos vazios em verde neon
          apple_color: "#FF69B4"        # Commits em rosa vibrante

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
