name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🐍 Versão para tema claro
      - name: Generate Snake (light)
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: itsfernandesb
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#C084FC"        # Lilás suave
          color_dots: "#D3D3D3"        # Cinza claro
          color_apple: "#22D3EE"       # Azul turquesa
          color_background: "#FFFFFF"  # Fundo branco para tema claro

      # 🌑 Versão para tema escuro
      - name: Generate Snake (dark)
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: itsfernandesb
          outputs: dist/github-contribution-grid-snake-dark.svg
          color_snake: "#C084FC"        # Lilás suave
          color_dots: "#30363D"        # Cinza escuro
          color_apple: "#22D3EE"       # Azul turquesa
          color_background: "#0D1117"  # Fundo escuro igual ao tema do GitHub

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
